
# Algoritmos de optimización - Seminario

Nombre y Apellidos: Salvador Díaz González

Url:

# Problema 1. Organizar sesiones de doblaje(I)

- (*) ¿Cuántas posibilidades hay sin tener en cuenta las restricciones?

La restricción que presenta el problema en este caso, es grabar como máximo 6 tomas al día, si quitamos esa restricción, significa que se puede grabar cualquier número de tomas en un día, si hay 30 tomas y 10 actores, pues se grabarían las 30 tomas en un solo día, se tomaría cualquier combinación de tomas que todas serían válidas y el coste siempre el mínimo. La combinación de tomas sería 30! y cualquiera de ellas daría el coste mínimo. En principio en este caso daría igual las permutaciones de filas.

IMPORTANTE: debido a la estructura de datos del problema, se pueden reducir el número de tomas, por ejemplo de 30 a 22, ya que existen tomas que pueden unirse en una sola toma sin que afecte al número de participaciones de cada actor en cada toma. Más adelante se muestra el código de como se realiza esa reducción. Por tanto en este caso habrían 22! de posibilidades de ubicar esas tomas pero el costo sería el mismo ya que el cobro es por actor y día, y como se comentó anteriormente, sin restricciones, todas las tomas se podrían realizar en un día.

Para simplificar, tomaremos que cada actor cobra una unidad monetaria o un sueldo, es decir, 1. Por tanto en cualquiera de los casos anteriores, si todas las tomas se grabasen en un día, el costo sería 10, ya que son 10 actores.


- ¿Cuántas posibilidades hay teniendo en cuenta todas las restricciones?

La restricción es 6 tomas por día.

Existen dos posibilidades:

   a) 30 tomas: sería tomar las combinaciones de los 30 elementos tomados de 6 en 6 sin repetición para el primer día, luego 24 elementos tomados de 6 en 6 sin repetición para el segundo día, etc.
    
   C(30,6) * C(24,6) * C(18,6) * C(12,6) * C(6,6) = 1,37·10^18 posibilidades.
   
   La fórmula es: C(a, b)= a! / (b! * (a - b)!).
   
   También: 30!/[(6!)^5]
    
   b) 22 tomas: sería tomar las combinaciones de los 22 elementos tomados de 6 en 6 sin repetición para el primer día, luego 16 elementos tomados de 6 en 6 sin repetición para el segundo día, etc.
   
   C(22,6) * C(16,6) * C(10,6) * 4 = 5,02·10^11 posibilidades.

Si hiciéramos 30! para hacer las combinaciones sería el caso en que sí nos importase por ejemplo qué día se realizan tales tomas y dentro del día que nos importase el orden de esas tomas. Pero para el costo no afecta las combinaciones de tomas dentro del grupo de 6 y en qué día se ubican esas tomas.



In [2]:
# COMBINACIONES 30 tomas
import math

tomas = 30
tomas_maximo = 6
dias = 5

combinaciones = math.comb(tomas, tomas_maximo) * math.comb(tomas - tomas_maximo, tomas_maximo) * math.comb(tomas - 2 * tomas_maximo, tomas_maximo) * math.comb(tomas - 3 * tomas_maximo, tomas_maximo) * math.comb(tomas - 4 * tomas_maximo, tomas_maximo)

print("Combinaciones en 5 días:", combinaciones)

# COMBINACIONES 22 tomas
tomas = 22
tomas_maximo = 6
dias = 3

combinaciones = (math.comb(tomas, tomas_maximo) * math.comb(tomas - tomas_maximo, tomas_maximo) * math.comb(tomas - 2 * tomas_maximo, tomas_maximo))*4

print("Combinaciones en 4 días:", combinaciones)

Combinaciones en 5 días: 1370874167589326400
Combinaciones en 4 días: 501900759360


 - (*) ¿Cuál es la estructura de datos que mejor se adapta al problema? Argumenta la respuesta (Es posible que hayas elegido una al principio y veas la necesidad de cambiar, argumenta)

Para este problema concreto, es suficiente con una lista de listas, es cierto que se puede emplear un np.array pero los cálculos que se realizan son básicamente intercambio de filas y sumas. Por tanto utilizar una lista de listas o un np.array es lo mismo. Aquí he optado por la lista de listas. Cada fila representaría el número de tomas y cada columna el actor. Tomando como ejemplo la matriz de 30x10, el elemento M(0,0)=1 significa que el actor 1 participa en la toma 1.
Se podía elegir también un DataFrame para resolver el problema y aunque mejoraría la visualización, en cuánto a tiempo de proceso y por la simplicidad de los datos es mejor lista de listas o np.array. Si hubiesen más datos de cada actor y de las tomas que hubiese que tener en cuenta, sí sería conveniente usar un DataFrame, pero al ser datos binarios y todas las filas tienen el mismo significado (tomas) e igual las columnas (actores) es recomendable lo comentado anteriormente.


- (*) ¿Cuál es la función objetivo?

La función objetivo es el costo, para ello se pretende que cada día vayan el mayor número posible de actores sin que se superen las 6 tomas por día, esto también restrige el número de veces que un actor puede participar por día, como es lógico es 6 también.
Como ya se comentó, se puede acordar (por simplificación) que cada actor cobre por día una unidad monetaria o un sueldo, es decir, 1, por tanto la función de costes sería sumar 1 si en la columna del actor (independientemente si aparece más de un 1 en la columna) aparece un 1 en cualquier posición. Por ejemplo, para el caso a) 30 tomas, para el primer día se puede obtener una solución tal que:

Día 1

[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]

[0, 0, 1, 1, 1, 0, 0, 0, 0, 0]

[0, 1, 0, 0, 1, 0, 1, 0, 0, 0]

[1, 1, 0, 0, 0, 0, 1, 1, 0, 0]

[0, 1, 0, 1, 0, 0, 0, 1, 0, 0]

[1, 1, 0, 1, 1, 0, 0, 0, 0, 0]

Suma parcial del costo: 7

En todas las columnas aparece al menos un 1 en las 7 primeras columnas en alguna posición, las dos últimas columnas tienen 0 en todas sus filas, lo que se traduce a sumar 1 por cada vez que aparezca un 1 en la columna (aunque se repita se cuenta solo 1), con lo que sumando sería 1 + 1 + 1 + 1+ 1 + 1 + 1 = 7.

Se calcularía ese costo parcial para cada uno de los 5 días y se sumaría.



In [5]:
# A) Costo de la matriz con 30 tomas, sin permutaciones ni variaciones de ningún tipo, solo función de
# costo.

def calcular_costo(matriz):
    actores_presentes = [0] * len(matriz[0])
    costo = 0
    tomas_por_dia = 6
    filas_empleadas = []
    suma_parcial_costo = 0

    for i, fila in enumerate(matriz):
        for j, participacion in enumerate(fila):
            if participacion == 1:
                actores_presentes[j] = 1

        filas_empleadas.append(fila)
        
        # Para calcular el costo por día al llegar a 6 tomas
        if (i + 1) % tomas_por_dia == 0 or i == len(matriz) - 1:
            costo_dia = sum(actores_presentes)
            suma_parcial_costo += costo_dia
            costo += costo_dia
            print("Día", (i // tomas_por_dia) + 1)
            for fila_empleada in filas_empleadas:
                print(fila_empleada)
            print("Costo parcial del día:", suma_parcial_costo)
            print()
            actores_presentes = [0] * len(matriz[0])
            filas_empleadas = []
            suma_parcial_costo = 0

    return costo

matriz = [
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
]

costo_total = calcular_costo(matriz)
print("Costo total:", costo_total)


Día 1
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
[0, 0, 1, 1, 1, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 1, 0, 1, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 1, 1, 0, 0]
[0, 1, 0, 1, 0, 0, 0, 1, 0, 0]
[1, 1, 0, 1, 1, 0, 0, 0, 0, 0]
Costo parcial del día: 7

Día 2
[1, 1, 0, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 1, 0, 0, 0, 0]
[1, 1, 0, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 1, 0, 0, 1, 0]
[1, 1, 1, 0, 1, 0, 0, 1, 0, 0]
[1, 1, 1, 1, 0, 1, 0, 0, 0, 0]
Costo parcial del día: 8

Día 3
[1, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[1, 0, 1, 0, 0, 1, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 1, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 0, 0, 1]
[1, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 1, 0, 0, 0, 0]
Costo parcial del día: 8

Día 4
[1, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 1, 1, 1, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 0, 1, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 1, 0, 0, 0, 0]
Costo parcial del día: 7

Día 5
[1, 1, 0, 1, 0, 0, 0, 0, 0, 1]
[1, 0, 1, 0, 1, 0, 0, 0, 1, 0]
[0, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[1, 0, 0, 1, 0, 0, 0, 0, 0, 0

In [7]:
# REDUCCIÓN de la matriz de 30 filas a 22.
'''
Existen otras combinaciones para convertir la matriz de 30 tomas en una de 22 tomas, incluso crear un
código para intentar reducir más aún la matriz. Pero en este caso se ha optado por lo siguiente: en el
código se coge la toma 1 y verifica si puede combinarse, es decir, sumarse sin que ningún valor de la
fila sea > 1.
Ej: toma la fila 0, comprueba si puede sumarla a la fila 1 sin que ningún valor de la fila sea > 1,
si NO sucede, lo comprueba con la fila 2 (es decir la 0 con la 1 y con la 2), en caso que sí suceda salta a
la siguiente fila y vuelve a comprobar con las restantes y así hasta que encuentra la combinación, en este
caso encuentra que la fila 0 se puede sumar a la 20, guarda los índices como tupla que sí se han podido
sumar y vuelve a repetir con la fila 1 con el resto, y así encuentra la matriz de 22 filas.
'''

def reducir_filas(mat):
    filas = len(mat)
    cols = len(mat[0])
    matriz_r = mat.copy()

    # Las filas que se han sumado se deben eliminar, por eso se marcan.
    filas_marcada = [False] * filas
    tupla_sum = []

    for i in range(filas):
        if not filas_marcada[i]:
            # Para sumar la fila actual con las filas restantes.
            for j in range(i + 1, filas):
                if not filas_marcada[j] and j not in [op[0] for op in tupla_sum]:
                    # Ahora comprobamos que no hay valores > 1.
                    sum_row = [a + b for a, b in zip(matriz_r[i], matriz_r[j])]
                    if any(value > 1 for value in sum_row):
                        continue  # Si sucede que al sumar es > 1, continua.

                    # Reemplazar la fila i por la suma de las filas i y j
                    matriz_r[i] = sum_row
                    filas_marcada[j] = True

                    # Añade una tupla que indica que filas se han sumado.
                    tupla_sum.append((i, j))

    # Eliminar las filas marcadas
    matriz_r = [filas for filas, marked in zip(matriz_r, filas_marcada) if not marked]

    return matriz_r, tupla_sum

matriz = [
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
]

filas_reducidas, operations = reducir_filas(matriz)

# Para imprimir las filas que se han podido sumar y la matriz reducida.
for operation in operations:
    print(f"Filas sumadas: {operation[0]} y {operation[1]}")

print("Matriz reducida:")
for filas in filas_reducidas:
    print(filas)

Filas sumadas: 0 y 20
Filas sumadas: 1 y 3
Filas sumadas: 2 y 13
Filas sumadas: 2 y 15
Filas sumadas: 4 y 16
Filas sumadas: 5 y 17
Filas sumadas: 6 y 23
Filas sumadas: 7 y 26
Matriz reducida:
[1, 1, 1, 1, 1, 1, 0, 1, 0, 0]
[1, 1, 1, 1, 1, 0, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 1]
[1, 1, 1, 1, 0, 0, 0, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
[1, 1, 0, 1, 1, 1, 0, 0, 0, 0]
[1, 1, 0, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 1, 0, 0, 1, 0]
[1, 1, 1, 0, 1, 0, 0, 1, 0, 0]
[1, 1, 1, 1, 0, 1, 0, 0, 0, 0]
[1, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 1, 0, 0, 0]
[1, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 1, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 0, 0, 0, 0, 0, 1]
[1, 0, 1, 0, 1, 0, 0, 0, 1, 0]
[1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 1, 1, 0, 0, 0, 0]
[1, 0, 0, 1, 0, 0, 0, 0, 0, 0]


En el caso:

Filas sumadas: 2 y 13

Filas sumadas: 2 y 15

Se suma 2, 13 y 15. Sería la fila 3 (la 2):  [1, 1, 1, 1, 1, 1, 1, 0, 0, 1].


In [4]:
# B) Costo de la matriz con 22 tomas (la matriz anterior), sin permutaciones ni variaciones de ningún
# tipo, solo función de costo.

def calcular_costo(matriz):
    actores_presentes = [0] * len(matriz[0])
    costo = 0
    tomas_por_dia = 6
    filas_empleadas = []
    suma_parcial_costo = 0

    for i, fila in enumerate(matriz):
        for j, participacion in enumerate(fila):
            if participacion == 1:
                actores_presentes[j] = 1

        filas_empleadas.append(fila)

        # Para calcular el costo por día hasta completar el número de tomas.
        if (i + 1) % tomas_por_dia == 0 or i == len(matriz) - 1:
            costo_dia = sum(actores_presentes)
            suma_parcial_costo += costo_dia
            costo += costo_dia
            print("Día", (i // tomas_por_dia) + 1)
            for fila_empleada in filas_empleadas:
                print(fila_empleada)
            print("Costo parcial del día:", suma_parcial_costo)
            print()
            actores_presentes = [0] * len(matriz[0])
            filas_empleadas = []
            suma_parcial_costo = 0

    return costo

matriz = [
    [1, 1, 1, 1, 1, 1, 0, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 1, 1, 0, 0, 1],
    [1, 1, 1, 1, 0, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 1, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 1, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
]

costo_total = calcular_costo(matriz)
print("Costo total:", costo_total)


Día 1
[1, 1, 1, 1, 1, 1, 0, 1, 0, 0]
[1, 1, 1, 1, 1, 0, 1, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 1, 0, 0, 1]
[1, 1, 1, 1, 0, 0, 0, 1, 0, 0]
[1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
Costo parcial del día: 9

Día 2
[1, 1, 0, 1, 1, 1, 0, 0, 0, 0]
[1, 1, 0, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 1, 0, 0, 1, 0]
[1, 1, 1, 0, 1, 0, 0, 1, 0, 0]
[1, 1, 1, 1, 0, 1, 0, 0, 0, 0]
[1, 0, 0, 1, 1, 0, 0, 0, 0, 0]
Costo parcial del día: 8

Día 3
[1, 1, 0, 0, 0, 0, 1, 0, 0, 0]
[1, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 1, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 0, 0, 0, 0, 0, 1]
Costo parcial del día: 7

Día 4
[1, 0, 1, 0, 1, 0, 0, 0, 1, 0]
[1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 1, 1, 0, 0, 0, 0]
[1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
Costo parcial del día: 6

Costo total: 30


- (*) ¿Es un problema de maximización o minimización?

Se trata de minimizar el coste. Minimización.


- Diseña un algoritmo para resolver el problema por fuerza bruta.

Realizado a continuación.



In [7]:
# Algoritmo Fuerza Bruta
# Utilizamos intertools, para realizar todas las permutaciones entre filas posibles.

import random
import itertools

def calcular_costo(mat):
    actores_presentes = [0] * len(mat[0])
    costo = 0
    tomas_por_dia = 6
    filas_empleadas = []
    suma_parcial_costo = 0

    for i, fila in enumerate(mat):
        for j, participacion in enumerate(fila):
            if participacion == 1:
                actores_presentes[j] = 1

        filas_empleadas.append(fila)

        # Calcular el costo por día hasta completar el número de tomas.
        if (i + 1) % tomas_por_dia == 0 or i == len(mat) - 1:
            costo_dia = sum(actores_presentes)
            suma_parcial_costo += costo_dia
            costo += costo_dia
            actores_presentes = [0] * len(mat[0])
            filas_empleadas = []
            suma_parcial_costo = 0

    return costo

def permutar_filas(matr, fila1, fila2):
    matr[fila1], matr[fila2] = matr[fila2], matr[fila1]

def fuerza_bruta(matriz):
    mejor_costo = float('inf') # inicializamos el costo en infinito.
    mejor_matriz = None
    mejor_matriz_dias = None

    # Generar todas las permutaciones posibles de las filas.
    filas = list(range(len(matriz)))
    combinaciones_filas = itertools.permutations(filas)

    for combinacion in combinaciones_filas:
        matriz_actual = [matriz[i] for i in combinacion]
        
        # Dividir las filas en grupos de 6 para cada día.
        dias = [matriz_actual[i:i+6] for i in range(0, len(matriz_actual), 6)]
        
        # Calcular el costo para la matriz actual y los costos parciales por día.
        costo_actual = 0
        costos_parciales = []
        for dia in dias:
            costo_dia = calcular_costo(dia)
            costo_actual += costo_dia
            costos_parciales.append(costo_dia)
        
        # Actualizar la mejor matriz y costo si corresponde.
        if costo_actual < mejor_costo:
            mejor_costo = costo_actual
            mejor_matriz = [fila[:] for fila in matriz_actual]
            mejor_matriz_dias = [dia[:] for dia in dias]

    return mejor_costo, mejor_matriz, mejor_matriz_dias

# Como ejemplo se usa una matriz reducida.
matriz = [
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0]
]

mejor_costo, mejor_matriz, mejor_matriz_dias = fuerza_bruta(matriz)

print("\nMatriz por días:")
for i, dia in enumerate(mejor_matriz_dias, 1):
    print(f"\nDía {i}:")
    for fila in dia:
        print(fila)

print("\nCosto parcial por día:")
for i, costo_dia in enumerate(mejor_matriz_dias, 1):
    print(f"Día {i}: {calcular_costo(costo_dia)}")

print("Mejor costo encontrado:", mejor_costo)

print("\nMatriz de menor costo:")
for fila in mejor_matriz:
    print(fila)



Matriz por días:

Día 1:
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
[0, 0, 1, 1, 1, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 1, 0, 1, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 1, 1, 0, 0]
[0, 1, 0, 1, 0, 0, 0, 1, 0, 0]
[1, 1, 0, 1, 1, 0, 0, 0, 0, 0]

Día 2:
[1, 1, 0, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 1, 0, 0, 0, 0]
[1, 1, 0, 1, 0, 0, 0, 0, 0, 0]

Costo parcial por día:
Día 1: 7
Día 2: 5
Mejor costo encontrado: 12

Matriz de menor costo:
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
[0, 0, 1, 1, 1, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 1, 0, 1, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 1, 1, 0, 0]
[0, 1, 0, 1, 0, 0, 0, 1, 0, 0]
[1, 1, 0, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 1, 0, 0, 0, 0]
[1, 1, 0, 1, 0, 0, 0, 0, 0, 0]


- Calcula la complejidad del algoritmo por fuerza bruta.

Generar todas las permutaciones posibles ya implica una complejidad O(n!).

El cálculo de dividir en grupos de 6 tomas tiene una complejidad lineal O(n).

El cálculo de la función de costos, recorriendo las filas y columnas sumando la precencia de un actor o no es O(n*m).

Como O(n!) crece mucho más rápido que las otras dos, se concluye que la complejidad computacional es factorial.




- (*) Diseña un algoritmo que mejore la complejidad del algoritmo por fuerza bruta.

Los algoritmos encontrados para resolver el problema siempren tienen un cierto carácter de fuerza bruta, aunque es cierto que el algoritmo que se propone a continuación, parte de una solución inicial, y permuta dos filas calculando el costo, lo que puede entenderse como una búsqueda local, no deja de ser finalmente fuerza bruta limitando el número de iteraciones. La limitación de iteraciones puede hacerse de dos maneras, o bien fijando el número concreto de las mismas, o forzar la detención del código si después de un número de iteraciones fijado por nosotros no encuentra una mejor solución.
Un algoritmo voraz devuelve soluciones mucho peores que la propuesta en este caso.
A continuación se muestra el código de "búsqueda local".


In [2]:
# Código de Búsqueda Local con la matriz de 30 tomas.

import random

def calcular_costo(matriz):
    actores_presentes = [0] * len(matriz[0])
    costo = 0
    tomas_por_dia = 6
    filas_empleadas = []
    suma_parcial_costo = 0

    for i, fila in enumerate(matriz):
        for j, participacion in enumerate(fila):
            if participacion == 1:
                actores_presentes[j] = 1

        filas_empleadas.append(fila)

        # Para calcular el costo por día cuando se alcanza el número máximo de tomas (6).
        if (i + 1) % tomas_por_dia == 0 or i == len(matriz) - 1:
            costo_dia = sum(actores_presentes)
            suma_parcial_costo += costo_dia
            costo += costo_dia
            actores_presentes = [0] * len(matriz[0])
            filas_empleadas = []

    return costo

def permutar_filas(matriz, fila1, fila2):
    matriz[fila1], matriz[fila2] = matriz[fila2], matriz[fila1]

mat = [
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
]


mejor_costo = float('inf')  # Inicializar el mejor costo con infinito
mejor_matriz = []  # Inicializar la matriz con el mejor costo
orden_filas_mejor_matriz = []  # Inicializar la lista de orden de filas de la mejor matriz
mejores_submatrices = []  # Inicializar la lista para almacenar las mejores submatrices y sus costos parciales

# Se crea un diccionario para mantener el orden original de las filas
orden_original = {tuple(row): idx + 1 for idx, row in enumerate(mat)}

for _ in range(100000):
    fila1 = random.randint(0, len(mat) - 1) # selección de filas aleatoriamente.
    fila2 = random.randint(0, len(mat) - 1)
    permutar_filas(mat, fila1, fila2) # Se intercambian.
    costo_actual = calcular_costo(mat)
    if costo_actual < mejor_costo: # comparación del costo y actualización del costo en caso de ser mejor.
        mejor_costo = costo_actual # actualización.
        mejor_matriz = [fila[:] for fila in mat]  # Se crea la copia de la matriz actual.

# Para obtener el orden de las filas en la matriz de menor costo en función del orden de la matriz inicial.
for fila in mejor_matriz:
    indice_fila = orden_original[tuple(fila)]  # tupla que se utilizará como clave para encontrar el valor del índice en la matriz inicial.
    orden_filas_mejor_matriz.append(indice_fila)

# Para obtener las 5 submatrices de 6 filas cada una.
num_submatrices = len(mejor_matriz) // 6
for i in range(num_submatrices):
    inicio = i * 6
    fin = inicio + 6
    submatriz = mejor_matriz[inicio:fin]
    costo_submatriz = calcular_costo(submatriz)
    mejores_submatrices.append((submatriz, costo_submatriz))

print("Último mejor costo:", mejor_costo)

print("Orden de tomas en la matriz de menor costo:")
print(orden_filas_mejor_matriz)

print("Matriz con menor costo:")
for fila in mejor_matriz:
    print(fila)

print("\nMejores submatrices y sus costos parciales:")
for i, (submatriz, costo_parcial) in enumerate(mejores_submatrices):
    print(f"\nSubmatriz {i+1}:")
    for fila in submatriz:
        print(fila)
    print(f"Costo parcial: {costo_parcial}")

Último mejor costo: 32
Orden de tomas en la matriz de menor costo:
[16, 20, 22, 7, 26, 25, 23, 8, 10, 3, 11, 29, 5, 9, 21, 15, 4, 30, 12, 13, 1, 7, 24, 24, 23, 30, 27, 23, 14, 2]
Matriz con menor costo:
[0, 0, 0, 1, 0, 0, 0, 0, 0, 1]
[1, 0, 1, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 1, 0, 0, 0, 0, 0]
[1, 0, 1, 0, 1, 0, 0, 0, 1, 0]
[1, 1, 0, 1, 0, 0, 0, 0, 0, 1]
[1, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 1, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 1, 0, 0, 1, 0]
[0, 1, 0, 0, 1, 0, 1, 0, 0, 0]
[1, 1, 1, 0, 1, 0, 0, 1, 0, 0]
[1, 0, 0, 0, 1, 1, 0, 0, 0, 0]
[0, 1, 0, 1, 0, 0, 0, 1, 0, 0]
[1, 1, 0, 1, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 0, 1, 0, 0]
[1, 1, 0, 0, 0, 0, 1, 0, 0, 0]
[1, 1, 0, 0, 0, 0, 1, 1, 0, 0]
[1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 0, 1, 0, 0, 0, 0]
[1, 0, 0, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
[1, 1, 0, 1, 1, 0, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 1, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 1, 0, 0, 0, 0]
[1, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 1, 0, 0, 0, 

In [7]:
# Código de búsqueda local con la matriz de 22 tomas.
import numpy as np
import random

def calcular_costo(matriz):
    actores_presentes = [0] * len(matriz[0])
    costo = 0
    tomas_por_dia = 6
    filas_empleadas = []
    suma_parcial_costo = 0

    for i, fila in enumerate(matriz):
        for j, participacion in enumerate(fila):
            if participacion == 1:
                actores_presentes[j] = 1

        filas_empleadas.append(fila)

        # Para calcular el costo por día cuando se alcanza el número máximo de tomas (6).
        if (i + 1) % tomas_por_dia == 0 or i == len(matriz) - 1:
            costo_dia = sum(actores_presentes)
            suma_parcial_costo += costo_dia
            costo += costo_dia
            actores_presentes = [0] * len(matriz[0])
            filas_empleadas = []

    return costo

def permutar_filas(matriz, fila1, fila2):
    matriz[fila1], matriz[fila2] = matriz[fila2], matriz[fila1]

mat = [
    [1, 1, 1, 1, 1, 1, 0, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 1, 1, 0, 0, 1],
    [1, 1, 1, 1, 0, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
    [1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 1, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 1, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
]


mejor_costo = float('inf')  # Inicializar el mejor costo con infinito.
mejor_matriz = []  # Inicializar la matriz con el mejor costo.
orden_filas_mejor_matriz = []  # Inicializar la lista de orden de filas de la mejor matriz.
mejores_submatrices = []  # Inicializar la lista para almacenar las mejores submatrices y sus costos parciales.

# Crear un diccionario para mantener el orden original de las filas.
orden_original = {tuple(row): idx + 1 for idx, row in enumerate(mat)}

for _ in range(100000):
    fila1 = random.randint(0, len(mat) - 1)
    fila2 = random.randint(0, len(mat) - 1)
    permutar_filas(mat, fila1, fila2)
    costo_actual = calcular_costo(mat)
    if costo_actual < mejor_costo:
        mejor_costo = costo_actual
        mejor_matriz = [fila[:] for fila in mat]  # Hacer una copia de la matriz actual.

# Obtener el orden de las filas en la matriz de menor costo usando el diccionario.
for fila in mejor_matriz:
    indice_fila = orden_original[tuple(fila)]  # Recuperar el índice original.
    orden_filas_mejor_matriz.append(indice_fila)

# Obtener las 5 submatrices de 6 filas cada una.
num_submatrices = len(mejor_matriz) // 6
for i in range(num_submatrices):
    inicio = i * 6
    fin = inicio + 6
    submatriz = mejor_matriz[inicio:fin]
    costo_submatriz = calcular_costo(submatriz)
    mejores_submatrices.append((submatriz, costo_submatriz))

print("Último mejor costo:", mejor_costo)

# Imprimir el orden de las filas en la matriz de menor costo.
print("Orden de tomas en la matriz de menor costo:")
print(orden_filas_mejor_matriz)

# Imprimir la matriz con el mejor costo encontrado.
matriz_menor_costo = np.array(mejor_matriz)
print("Matriz con menor costo:")
print(matriz_menor_costo)

# Imprimir las submatrices y sus costos parciales.
print("\nMejores submatrices y sus costos parciales:")
for i, (submatriz, costo_parcial) in enumerate(mejores_submatrices):
    print(f"\nSubmatriz {i+1}:")
    for fila in submatriz:
        print(fila)
    print(f"Costo parcial: {costo_parcial}")



# Comprobación que ambas matrices poseen las mismas tomas.
def comparar_matrices(matriz1, matriz2):
    # Verificar que tengan la misma cantidad de filas.
    if len(matriz1) != len(matriz2):
        return False

    # Convertir las filas de ambas matrices en conjuntos.
    set_matriz1 = set(map(tuple, matriz1))
    set_matriz2 = set(map(tuple, matriz2))

    # Verificar que todas las filas de matriz1 estén en matriz2.
    return set_matriz1.issubset(set_matriz2)

print('Matrices iguales: ', comparar_matrices(matriz_menor_costo,mat))

Último mejor costo: 27
Orden de tomas en la matriz de menor costo:
[6, 8, 1, 2, 4, 12, 6, 9, 10, 19, 7, 11, 21, 13, 15, 3, 16, 18, 17, 22, 22, 17]
Matriz con menor costo:
[[1 1 1 1 1 1 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 0]
 [1 1 1 1 1 1 0 1 0 0]
 [1 1 1 1 1 0 1 1 0 0]
 [1 1 1 1 0 0 0 1 0 0]
 [1 0 0 1 1 0 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0]
 [1 1 0 0 0 1 0 0 1 0]
 [1 1 1 0 1 0 0 1 0 0]
 [1 0 1 0 1 0 0 0 1 0]
 [1 1 0 1 1 1 0 0 0 0]
 [1 1 1 1 0 1 0 0 0 0]
 [1 0 0 0 1 1 0 0 0 0]
 [1 1 0 0 0 0 1 0 0 0]
 [1 0 1 1 1 0 0 0 0 0]
 [1 1 1 1 1 1 1 0 0 1]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]]

Mejores submatrices y sus costos parciales:

Submatriz 1:
[1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
[1, 1, 0, 1, 0, 0, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 0, 1, 0, 0]
[1, 1, 1, 1, 1, 0, 1, 1, 0, 0]
[1, 1, 1, 1, 0, 0, 0, 1, 0, 0]
[1, 0, 0, 1, 1, 0, 0, 0, 0, 0]
Costo parcial: 8

Submatriz 2:
[1, 1, 1, 1, 1, 1, 0, 0, 0, 0]
[1, 1, 0, 0, 0,

- Argumenta porque crees que mejora el algoritmo por fuerza bruta.

Lo mejora que introduce el algoritmo de búsqueda local es en tiempo de ejecución ya que reduce considerablemente el número de permutación de filas que realiza, de hecho se introduce como parámetro elegible. Además es una solución válida para tamaño de matrices grandes, donde por fuerza bruta sería imposible de ejecutar en tiempos razonables.

Por contra, se trata de un método heurístico y por tanto no garantiza la solución óptima.


- (*) Calcula la complejidad del algoritmo.
El algoritmo de búsqueda local posee una complejidad de O(k * n), siendo "k" es el número de iteraciones que realiza el algoritmo y "n" es el número de filas en la matriz.

En cada iteración, el algoritmo realiza dos operaciones principales:

- El código crea dos índices aleatorios con lo que elige dos filas al azar que intercambia.

- El cálculo del costo de la nueva matriz  y comparar si el costo es menor que el mejor costo encontrado hasta el momento.

El algoritmo repite estas dos operaciones "k" veces, y en cada iteración requiere un tiempo constante en el intercambio de filas y para calcular el costo, lo que se llega a que la complejidad total del algoritmo es proporcional a k * n.



- Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorio.

Realizado a continuación.

In [11]:
import random
import numpy as np

def generar_matriz_aleatoria(n, m):
    matriz = np.random.randint(0, 2, size=(n, m))
    return matriz

def convertir_matriz(matriz):
    mat = []
    for fila in matriz:
        tomas_fila = [1 if val == 1 else 0 for val in fila]
        mat.append(tomas_fila)
    return mat

# Ejemplo
filas = 30
columnas = 10

matriz_aleatoria = generar_matriz_aleatoria(filas, columnas)

print("Matriz aleatoria:")
print(matriz_aleatoria)

mat = convertir_matriz(matriz_aleatoria)

print("\nMatriz convertida:")
for fila in mat:
    print(fila)




Matriz aleatoria:
[[1 1 0 0 0 1 0 0 1 1]
 [1 0 0 1 1 0 0 0 0 1]
 [1 0 1 0 1 0 1 0 0 0]
 [1 0 1 0 1 1 1 1 0 1]
 [1 1 0 1 1 1 1 1 1 1]
 [0 0 1 0 1 1 1 0 1 0]
 [0 0 0 1 1 1 0 0 0 0]
 [1 1 0 0 0 1 1 1 0 1]
 [0 1 0 0 1 0 0 0 1 0]
 [0 1 1 0 0 0 0 1 1 0]
 [1 0 0 1 1 1 0 1 0 0]
 [1 0 1 1 0 1 1 0 0 0]
 [0 0 1 0 1 0 0 0 0 1]
 [0 1 0 0 0 1 1 0 0 1]
 [0 0 0 1 0 1 1 0 1 0]
 [0 1 1 0 1 1 0 0 0 0]
 [0 1 1 0 0 1 0 0 0 1]
 [0 1 0 1 1 0 0 1 1 0]
 [1 1 1 0 1 0 1 1 1 1]
 [0 0 1 1 0 1 1 1 0 1]
 [0 1 1 0 1 1 0 1 1 0]
 [0 1 1 1 1 0 0 0 1 1]
 [1 1 1 1 1 0 0 1 1 0]
 [0 0 1 0 0 1 1 1 1 1]
 [0 1 0 0 0 0 1 0 1 0]
 [1 1 1 1 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 1 1]
 [0 1 1 0 1 1 0 1 0 1]
 [0 0 0 1 0 0 0 0 1 1]
 [0 1 1 1 1 0 0 1 0 0]]

Matriz convertida:
[1, 1, 0, 0, 0, 1, 0, 0, 1, 1]
[1, 0, 0, 1, 1, 0, 0, 0, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0, 0, 0]
[1, 0, 1, 0, 1, 1, 1, 1, 0, 1]
[1, 1, 0, 1, 1, 1, 1, 1, 1, 1]
[0, 0, 1, 0, 1, 1, 1, 0, 1, 0]
[0, 0, 0, 1, 1, 1, 0, 0, 0, 0]
[1, 1, 0, 0, 0, 1, 1, 1, 0, 1]
[0, 1, 0, 0, 1, 0, 0, 0